
# syntax=docker/dockerfile:1

# Dev dockerfile, do not use in production

ARG PYTHON_VERSION=3.12.0
FROM python:${PYTHON_VERSION}-slim as base

ENV APP_HOME=/backend
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY requirements.txt ./requirements.txt
COPY requirements-dev.txt ./requirements-dev.txt
RUN python -m pip install -r ./requirements.txt
RUN python -m pip install -r ./requirements-dev.txt

# copies the full backend directory
# Note: we are not mounting it because we will use docker watch to check for changes
COPY ./backend .

EXPOSE 8000

# Run the application, reloads on file change
CMD ["uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8000", "--reload" ]
